-- SQL Schema for Project Inventario (Supabase PostgreSQL)

-- 1. Create Units Table
CREATE TABLE IF NOT EXISTS unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Groups Table
CREATE TABLE IF NOT EXISTS grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS productos (
    codigo VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    unidad_id BIGINT REFERENCES unidades(id) ON DELETE RESTRICT,
    grupo_id BIGINT REFERENCES grupos(id) ON DELETE RESTRICT,
    stock_min INT DEFAULT 0 CHECK (stock_min >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Movements Table
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_codigo VARCHAR(50) REFERENCES productos(codigo) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    tipo VARCHAR(50) CHECK (tipo IN ('INGRESO', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', 'AJUSTE')),
    cantidad NUMERIC(10, 2) CHECK (cantidad > 0),
    usuario VARCHAR(255) NOT NULL,
    observaciones TEXT,
    key VARCHAR(50) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Create Real-Time Stock Database View
CREATE OR REPLACE VIEW v_productos_stock AS
SELECT 
    p.codigo,
    p.nombre,
    u.nombre AS unidad,
    g.nombre AS grupo,
    p.stock_min,
    COALESCE(
        SUM(
            CASE 
                WHEN m.tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN m.cantidad
                WHEN m.tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -m.cantidad
                ELSE 0
            END
        ), 
        0
    ) AS cantidad
FROM productos p
LEFT JOIN unidades u ON p.unidad_id = u.id
LEFT JOIN grupos g ON p.grupo_id = g.id
LEFT JOIN movimientos m ON p.codigo = m.producto_codigo
GROUP BY p.codigo, p.nombre, u.nombre, g.nombre, p.stock_min;

-- 6. Insert Default Units (Updated with your exact list)
INSERT INTO unidades (nombre) VALUES
('UND'), ('M'), ('M3'), ('KG'), ('GLB'), ('BAG'), ('ROL')
ON CONFLICT (nombre) DO NOTHING;

-- 7. Insert Default Groups
INSERT INTO grupos (nombre) VALUES
('General'), ('PAT'), ('BD'), ('CANAL')
ON CONFLICT (nombre) DO NOTHING;

-- 8. Enable Row Level Security (RLS)
ALTER TABLE unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos ENABLE ROW LEVEL SECURITY;

-- 9. Create Secure Policies for Authenticated Users (blocking anonymous public CRUD)
DROP POLICY IF EXISTS "Allow anonymous access on unidades" ON unidades;
DROP POLICY IF EXISTS "Allow authenticated access on unidades" ON unidades;
CREATE POLICY "Allow authenticated access on unidades" ON unidades FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous access on grupos" ON grupos;
DROP POLICY IF EXISTS "Allow authenticated access on grupos" ON grupos;
CREATE POLICY "Allow authenticated access on grupos" ON grupos FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous access on productos" ON productos;
DROP POLICY IF EXISTS "Allow authenticated access on productos" ON productos;
CREATE POLICY "Allow authenticated access on productos" ON productos FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous access on movimientos" ON movimientos;
DROP POLICY IF EXISTS "Allow authenticated access on movimientos" ON movimientos;
CREATE POLICY "Allow authenticated access on movimientos" ON movimientos FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 10. Create Administrators Table (for secure DNI verification)
CREATE TABLE IF NOT EXISTS administradores (
    dni VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on administradores table (No read/write policies created for anon role for security)
ALTER TABLE administradores ENABLE ROW LEVEL SECURITY;

-- Populate default authorized admin DNIs
INSERT INTO administradores (dni, nombre) VALUES
('48204199', 'Administrador Principal 1'),
('70429841', 'Administrador Principal 2')
ON CONFLICT (dni) DO NOTHING;

-- 11. Create Resets Log Table
CREATE TABLE IF NOT EXISTS historial_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(20) NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 12. Enable Row Level Security (RLS) on Resets Log Table
ALTER TABLE historial_resets ENABLE ROW LEVEL SECURITY;

-- 13. Create Permissive Policy for Anon Role to write/read reset history
DROP POLICY IF EXISTS "Allow anonymous access on historial_resets" ON historial_resets;
DROP POLICY IF EXISTS "Allow authenticated access on historial_resets" ON historial_resets;
CREATE POLICY "Allow authenticated access on historial_resets" ON historial_resets FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 14. Create Secure Reset Stored Function (SECURITY DEFINER allows bypassing direct table deletes)
CREATE OR REPLACE FUNCTION reset_sistema_autorizado(admin_dni TEXT)
RETURNS VOID AS $$
DECLARE
    is_authorized BOOLEAN;
BEGIN
    -- Validate DNI against secure database table
    SELECT EXISTS(
        SELECT 1 FROM administradores WHERE dni = admin_dni
    ) INTO is_authorized;

    IF NOT is_authorized THEN
        RAISE EXCEPTION 'Operación cancelada: El DNI ingresado no está autorizado.';
    END IF;

    -- Insert into reset log
    INSERT INTO historial_resets (dni) VALUES (admin_dni);

    -- Delete movements and products safely (WHERE clause satisfies safeupdate rules)
    DELETE FROM movimientos WHERE id IS NOT NULL;
    DELETE FROM productos WHERE codigo IS NOT NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
