-- SQL Schema for Project Inventario (Supabase PostgreSQL)
-- Updated with: Granular RLS, Rate-Limited Reset, Atomic Stock Validation, Audit Trail

-- ═══════════════════════════════════════════════════════════════
-- 1. CORE TABLES
-- ═══════════════════════════════════════════════════════════════

-- 1a. Units Table
CREATE TABLE IF NOT EXISTS unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 1b. Groups Table
CREATE TABLE IF NOT EXISTS grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 1c. Products Table
CREATE TABLE IF NOT EXISTS productos (
    codigo VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    unidad_id BIGINT REFERENCES unidades(id) ON DELETE RESTRICT,
    grupo_id BIGINT REFERENCES grupos(id) ON DELETE RESTRICT,
    stock_min INT DEFAULT 0 CHECK (stock_min >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 1d. Movements Table
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_codigo VARCHAR(50) REFERENCES productos(codigo) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    tipo VARCHAR(50) CHECK (tipo IN ('INGRESO', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', 'AJUSTE')),
    cantidad NUMERIC(10, 2) CHECK (cantidad > 0),
    usuario VARCHAR(255) NOT NULL,
    observaciones TEXT,
    key VARCHAR(50) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ═══════════════════════════════════════════════════════════════
-- 2. REAL-TIME STOCK VIEW
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW v_productos_stock AS
SELECT 
    p.codigo,
    p.nombre,
    u.nombre AS unidad,
    g.nombre AS grupo,
    p.stock_min,
    COALESCE(
        SUM(
            CASE 
                WHEN m.tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN m.cantidad
                WHEN m.tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -m.cantidad
                ELSE 0
            END
        ), 
        0
    ) AS cantidad
FROM productos p
LEFT JOIN unidades u ON p.unidad_id = u.id
LEFT JOIN grupos g ON p.grupo_id = g.id
LEFT JOIN movimientos m ON p.codigo = m.producto_codigo
GROUP BY p.codigo, p.nombre, u.nombre, g.nombre, p.stock_min;

-- ═══════════════════════════════════════════════════════════════
-- 3. DEFAULT SEED DATA
-- ═══════════════════════════════════════════════════════════════

INSERT INTO unidades (nombre) VALUES
('UND'), ('M'), ('M3'), ('KG'), ('GLB'), ('BAG'), ('ROL')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO grupos (nombre) VALUES
('General'), ('PAT'), ('BD'), ('CANAL')
ON CONFLICT (nombre) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- 4. ROW LEVEL SECURITY — GRANULAR POLICIES (SEC-2)
-- ═══════════════════════════════════════════════════════════════

-- Enable RLS on all core tables
ALTER TABLE unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos ENABLE ROW LEVEL SECURITY;

-- ── 4a. unidades: Read-only for all authenticated users (lookup table) ──
DROP POLICY IF EXISTS "Allow anonymous access on unidades" ON unidades;
DROP POLICY IF EXISTS "Allow authenticated access on unidades" ON unidades;
DROP POLICY IF EXISTS "unidades_select" ON unidades;
CREATE POLICY "unidades_select" ON unidades FOR SELECT TO authenticated USING (true);
-- INSERT/UPDATE/DELETE blocked by RLS (only manageable via Supabase dashboard / service key)

-- ── 4b. grupos: Read-only for all authenticated users (lookup table) ──
DROP POLICY IF EXISTS "Allow anonymous access on grupos" ON grupos;
DROP POLICY IF EXISTS "Allow authenticated access on grupos" ON grupos;
DROP POLICY IF EXISTS "grupos_select" ON grupos;
CREATE POLICY "grupos_select" ON grupos FOR SELECT TO authenticated USING (true);

-- ── 4c. productos: SELECT + INSERT for all authenticated; UPDATE allowed; DELETE restricted ──
DROP POLICY IF EXISTS "Allow anonymous access on productos" ON productos;
DROP POLICY IF EXISTS "Allow authenticated access on productos" ON productos;
DROP POLICY IF EXISTS "productos_select" ON productos;
DROP POLICY IF EXISTS "productos_insert" ON productos;
DROP POLICY IF EXISTS "productos_update" ON productos;
DROP POLICY IF EXISTS "productos_delete" ON productos;

CREATE POLICY "productos_select" ON productos FOR SELECT TO authenticated USING (true);
CREATE POLICY "productos_insert" ON productos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "productos_update" ON productos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
-- DELETE is intentionally not granted via RLS; only SECURITY DEFINER functions (like reset) can delete.

-- ── 4d. movimientos: SELECT + INSERT for all authenticated; no direct UPDATE/DELETE ──
DROP POLICY IF EXISTS "Allow anonymous access on movimientos" ON movimientos;
DROP POLICY IF EXISTS "Allow authenticated access on movimientos" ON movimientos;
DROP POLICY IF EXISTS "movimientos_select" ON movimientos;
DROP POLICY IF EXISTS "movimientos_insert" ON movimientos;
DROP POLICY IF EXISTS "movimientos_update" ON movimientos;

CREATE POLICY "movimientos_select" ON movimientos FOR SELECT TO authenticated USING (true);
CREATE POLICY "movimientos_insert" ON movimientos FOR INSERT TO authenticated WITH CHECK (true);
-- UPDATE is allowed only for upsert operations (import ingresos uses upsert on 'key' conflict)
CREATE POLICY "movimientos_update" ON movimientos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
-- DELETE is intentionally not granted; only SECURITY DEFINER functions can delete.

-- ═══════════════════════════════════════════════════════════════
-- 5. ADMINISTRATORS TABLE (for secure DNI verification)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS administradores (
    dni VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(100),
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE administradores ENABLE ROW LEVEL SECURITY;
-- No policies = no direct client access (secure by default)

INSERT INTO administradores (dni, nombre) VALUES
('48204199', 'Administrador Principal 1'),
('70429841', 'Administrador Principal 2')
ON CONFLICT (dni) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- 6. RESETS HISTORY TABLE
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS historial_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(20) NOT NULL,
    user_id UUID,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE historial_resets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous access on historial_resets" ON historial_resets;
DROP POLICY IF EXISTS "Allow authenticated access on historial_resets" ON historial_resets;
DROP POLICY IF EXISTS "historial_resets_select" ON historial_resets;
CREATE POLICY "historial_resets_select" ON historial_resets FOR SELECT TO authenticated USING (true);
-- INSERT only via SECURITY DEFINER functions

-- ═══════════════════════════════════════════════════════════════
-- 7. RATE-LIMITED RESET RPC (SEC-3)
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION reset_sistema_autorizado(admin_dni TEXT)
RETURNS VOID AS $$
DECLARE
    is_authorized BOOLEAN;
    recent_attempts INT;
BEGIN
    -- Rate limit: max 3 reset attempts per hour
    SELECT COUNT(*) INTO recent_attempts
    FROM historial_resets
    WHERE fecha > (NOW() - INTERVAL '1 hour');

    IF recent_attempts >= 3 THEN
        RAISE EXCEPTION 'Demasiados intentos de restablecimiento. Intente nuevamente en 1 hora.';
    END IF;

    -- Validate DNI against secure database table
    SELECT EXISTS(
        SELECT 1 FROM administradores WHERE dni = admin_dni
    ) INTO is_authorized;

    IF NOT is_authorized THEN
        -- Still log the failed attempt to count towards rate limit
        INSERT INTO historial_resets (dni, user_id) VALUES (admin_dni, auth.uid());
        RAISE EXCEPTION 'Operación cancelada: El DNI ingresado no está autorizado.';
    END IF;

    -- Log the authorized reset with user identity
    INSERT INTO historial_resets (dni, user_id) VALUES (admin_dni, auth.uid());

    -- Delete movements and products safely
    DELETE FROM movimientos WHERE id IS NOT NULL;
    DELETE FROM productos WHERE codigo IS NOT NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ═══════════════════════════════════════════════════════════════
-- 8. ATOMIC STOCK VALIDATION RPC (FUNC-5)
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION registrar_movimiento(
    p_producto_codigo VARCHAR(50),
    p_fecha DATE,
    p_tipo VARCHAR(50),
    p_cantidad NUMERIC(10, 2),
    p_usuario VARCHAR(255),
    p_observaciones TEXT DEFAULT '',
    p_key VARCHAR(50) DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
    stock_actual NUMERIC(10, 2);
    final_key VARCHAR(50);
    result JSONB;
BEGIN
    -- Validate product exists (with row-level lock to prevent concurrent modifications)
    PERFORM 1 FROM productos WHERE codigo = p_producto_codigo FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'El producto no existe.');
    END IF;

    -- Calculate current stock atomically
    SELECT COALESCE(SUM(
        CASE 
            WHEN tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN cantidad
            WHEN tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -cantidad
            ELSE 0
        END
    ), 0) INTO stock_actual
    FROM movimientos
    WHERE producto_codigo = p_producto_codigo;

    -- Validate stock for outgoing movements
    IF p_tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') AND stock_actual < p_cantidad THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', format('Stock insuficiente. Disponible: %s, Solicitado: %s', stock_actual, p_cantidad)
        );
    END IF;

    -- Handle transaction key
    IF p_key IS NOT NULL AND p_key != '' AND p_key != 'Automatico' THEN
        -- Check for duplicate key
        PERFORM 1 FROM movimientos WHERE key = p_key;
        IF FOUND THEN
            RETURN jsonb_build_object('success', false, 'error', 'Esta clave de transacción ya ha sido registrada.');
        END IF;
        final_key := p_key;
    ELSE
        -- Generate a unique key
        final_key := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10))
                  || '-' || upper(substr(md5(random()::text), 1, 3))
                  || '-' || upper(substr(md5(random()::text), 1, 2));
    END IF;

    -- Insert the movement
    INSERT INTO movimientos (producto_codigo, fecha, tipo, cantidad, usuario, observaciones, key)
    VALUES (p_producto_codigo, p_fecha, p_tipo, p_cantidad, p_usuario, p_observaciones, final_key);

    RETURN jsonb_build_object('success', true, 'key', final_key);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ═══════════════════════════════════════════════════════════════
-- 9. AUDIT LOG TABLE & TRIGGERS (FUNC-7)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla VARCHAR(100) NOT NULL,
    operacion VARCHAR(20) NOT NULL,
    registro_id TEXT,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    usuario_id UUID,
    usuario_email TEXT,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_log_select" ON audit_log;
CREATE POLICY "audit_log_select" ON audit_log FOR SELECT TO authenticated USING (true);
-- INSERT only via triggers (SECURITY DEFINER context)

-- Trigger function for productos
CREATE OR REPLACE FUNCTION audit_productos_trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_nuevos, usuario_id)
        VALUES ('productos', 'INSERT', NEW.codigo, to_jsonb(NEW), auth.uid());
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_anteriores, datos_nuevos, usuario_id)
        VALUES ('productos', 'UPDATE', NEW.codigo, to_jsonb(OLD), to_jsonb(NEW), auth.uid());
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_anteriores, usuario_id)
        VALUES ('productos', 'DELETE', OLD.codigo, to_jsonb(OLD), auth.uid());
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS audit_productos ON productos;
CREATE TRIGGER audit_productos
    AFTER INSERT OR UPDATE OR DELETE ON productos
    FOR EACH ROW EXECUTE FUNCTION audit_productos_trigger();

-- Trigger function for movimientos
CREATE OR REPLACE FUNCTION audit_movimientos_trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_nuevos, usuario_id)
        VALUES ('movimientos', 'INSERT', NEW.id::text, to_jsonb(NEW), auth.uid());
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_anteriores, datos_nuevos, usuario_id)
        VALUES ('movimientos', 'UPDATE', NEW.id::text, to_jsonb(OLD), to_jsonb(NEW), auth.uid());
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_log (tabla, operacion, registro_id, datos_anteriores, usuario_id)
        VALUES ('movimientos', 'DELETE', OLD.id::text, to_jsonb(OLD), auth.uid());
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS audit_movimientos ON movimientos;
CREATE TRIGGER audit_movimientos
    AFTER INSERT OR UPDATE OR DELETE ON movimientos
    FOR EACH ROW EXECUTE FUNCTION audit_movimientos_trigger();

-- ═══════════════════════════════════════════════════════════════
-- 10. REAL INTEGRITY VALIDATION RPC (SEC-6)
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION validar_integridad()
RETURNS JSONB AS $$
DECLARE
    orphaned_movements INT;
    negative_stock_count INT;
    invalid_tipo_count INT;
    result JSONB;
BEGIN
    -- Check for orphaned movements (producto_codigo not in productos)
    SELECT COUNT(*) INTO orphaned_movements
    FROM movimientos m
    WHERE NOT EXISTS (SELECT 1 FROM productos p WHERE p.codigo = m.producto_codigo);

    -- Check for products with negative calculated stock
    SELECT COUNT(*) INTO negative_stock_count
    FROM v_productos_stock
    WHERE cantidad < 0;

    -- Check for movements with invalid tipo values
    SELECT COUNT(*) INTO invalid_tipo_count
    FROM movimientos
    WHERE tipo NOT IN ('INGRESO', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', 'AJUSTE');

    result := jsonb_build_object(
        'orphaned_movements', orphaned_movements,
        'negative_stock', negative_stock_count,
        'invalid_tipos', invalid_tipo_count,
        'is_healthy', (orphaned_movements = 0 AND negative_stock_count = 0 AND invalid_tipo_count = 0)
    );

    RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ═══════════════════════════════════════════════════════════════
-- 11. AUTHORIZED MOVEMENT MANAGEMENT RPCs
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION eliminar_movimiento_autorizado(
    p_movimiento_id BIGINT,
    p_admin_dni TEXT
)
RETURNS VOID AS $$
DECLARE
    is_authorized BOOLEAN;
    v_producto_codigo VARCHAR(50);
    v_tipo VARCHAR(50);
    v_cantidad NUMERIC(10, 2);
    v_stock_actual NUMERIC(10, 2);
    v_impacto NUMERIC(10, 2);
BEGIN
    -- Validation bypassed as requested by user
    is_authorized := TRUE;

    -- 2. Get movement details and lock product row
    SELECT producto_codigo, tipo, cantidad INTO v_producto_codigo, v_tipo, v_cantidad
    FROM movimientos WHERE id = p_movimiento_id;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'El movimiento solicitado no existe.';
    END IF;

    PERFORM 1 FROM productos WHERE codigo = v_producto_codigo FOR UPDATE;

    -- 3. Calculate current stock
    SELECT COALESCE(SUM(
        CASE 
            WHEN tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN cantidad
            WHEN tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -cantidad
            ELSE 0
        END
    ), 0) INTO v_stock_actual
    FROM movimientos
    WHERE producto_codigo = v_producto_codigo;

    -- 4. Calculate stock impact if deleted
    IF v_tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN
        v_impacto := -v_cantidad;
    ELSE
        v_impacto := v_cantidad;
    END IF;

    -- 5. Block deletion if remaining stock would be negative
    IF (v_stock_actual + v_impacto) < 0 THEN
        RAISE EXCEPTION 'No se puede eliminar el movimiento: dejaría al producto % con stock negativo (Disponible: %, Reducción: %).', 
            v_producto_codigo, v_stock_actual, ABS(v_impacto);
    END IF;

    -- 6. Execute delete
    DELETE FROM movimientos WHERE id = p_movimiento_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE OR REPLACE FUNCTION editar_movimiento_autorizado(
    p_movimiento_id BIGINT,
    p_nueva_cantidad NUMERIC(10, 2),
    p_admin_dni TEXT
)
RETURNS VOID AS $$
DECLARE
    is_authorized BOOLEAN;
    v_producto_codigo VARCHAR(50);
    v_tipo VARCHAR(50);
    v_cantidad_anterior NUMERIC(10, 2);
    v_stock_actual NUMERIC(10, 2);
    v_diferencia NUMERIC(10, 2);
BEGIN
    -- Validation bypassed as requested by user
    is_authorized := TRUE;

    IF p_nueva_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad debe ser mayor a cero.';
    END IF;

    -- 2. Get current movement details and lock product row
    SELECT producto_codigo, tipo, cantidad INTO v_producto_codigo, v_tipo, v_cantidad_anterior
    FROM movimientos WHERE id = p_movimiento_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El movimiento solicitado no existe.';
    END IF;

    PERFORM 1 FROM productos WHERE codigo = v_producto_codigo FOR UPDATE;

    -- 3. Calculate current stock
    SELECT COALESCE(SUM(
        CASE 
            WHEN tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN cantidad
            WHEN tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -cantidad
            ELSE 0
        END
    ), 0) INTO v_stock_actual
    FROM movimientos
    WHERE producto_codigo = v_producto_codigo;

    -- 4. Calculate net difference
    IF v_tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN
        v_diferencia := p_nueva_cantidad - v_cantidad_anterior;
    ELSE
        v_diferencia := v_cantidad_anterior - p_nueva_cantidad;
    END IF;

    -- 5. Validate stock safety
    IF (v_stock_actual + v_diferencia) < 0 THEN
        RAISE EXCEPTION 'No se puede editar el movimiento: el cambio dejaría al producto % con stock negativo (Stock actual: %, Impacto neto: %).', 
            v_producto_codigo, v_stock_actual, v_diferencia;
    END IF;

    -- 6. Perform update
    UPDATE movimientos 
    SET cantidad = p_nueva_cantidad
    WHERE id = p_movimiento_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ═══════════════════════════════════════════════════════════════
-- 12. ADMIN USER ASSIGNMENT RPCs
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION es_administrador(p_dni TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS(SELECT 1 FROM administradores WHERE dni = p_dni);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE OR REPLACE FUNCTION crear_administrador_autorizado(
    p_admin_dni_autorizador TEXT,
    p_nuevo_dni TEXT,
    p_nuevo_nombre TEXT,
    p_nuevo_email TEXT
)
RETURNS VOID AS $$
DECLARE
    is_authorized BOOLEAN;
BEGIN
    -- 1. Validate that the person initiating the request is an admin
    SELECT EXISTS(
        SELECT 1 FROM administradores WHERE dni = p_admin_dni_autorizador
    ) INTO is_authorized;

    IF NOT is_authorized THEN
        RAISE EXCEPTION 'Operación cancelada: El DNI autorizador no tiene permisos de administrador.';
    END IF;

    -- 2. Insert new admin
    INSERT INTO administradores (dni, nombre, email)
    VALUES (p_nuevo_dni, p_nuevo_nombre, LOWER(p_nuevo_email))
    ON CONFLICT (dni) DO UPDATE 
    SET nombre = p_nuevo_nombre, email = LOWER(p_nuevo_email);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Migration: Add email column if updating an existing deployment
ALTER TABLE administradores ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;


-- RPC Function to check if email is admin and return their DNI
CREATE OR REPLACE FUNCTION obtener_dni_administrador(p_email TEXT)
RETURNS TEXT AS $$
DECLARE
    v_dni TEXT;
BEGIN
    SELECT dni INTO v_dni 
    FROM administradores 
    WHERE LOWER(email) = LOWER(p_email);
    
    RETURN v_dni;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to list all authentication users with their admin status
CREATE OR REPLACE FUNCTION listar_usuarios_sistema()
RETURNS TABLE (
    id UUID,
    email VARCHAR,
    created_at TIMESTAMPTZ,
    last_sign_in_at TIMESTAMPTZ,
    es_admin BOOLEAN,
    admin_dni VARCHAR,
    admin_nombre VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u.id,
        u.email::VARCHAR,
        u.created_at,
        u.last_sign_in_at,
        (a.dni IS NOT NULL) AS es_admin,
        a.dni::VARCHAR AS admin_dni,
        a.nombre::VARCHAR AS admin_nombre
    FROM auth.users u
    LEFT JOIN administradores a ON LOWER(u.email) = LOWER(a.email)
    ORDER BY u.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to promote a user to administrator
CREATE OR REPLACE FUNCTION asignar_administrador(
    p_user_email TEXT,
    p_dni TEXT,
    p_nombre TEXT
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO administradores (dni, nombre, email)
    VALUES (p_dni, p_nombre, LOWER(p_user_email))
    ON CONFLICT (dni) DO UPDATE
    SET nombre = p_nombre, email = LOWER(p_user_email);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to demote an administrator
CREATE OR REPLACE FUNCTION revocar_administrador(p_dni TEXT)
RETURNS VOID AS $$
BEGIN
    DELETE FROM administradores WHERE dni = p_dni;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to delete a user account from Auth and Administradores
CREATE OR REPLACE FUNCTION eliminar_usuario_sistema(p_user_id UUID)
RETURNS VOID AS $$
DECLARE
    v_email TEXT;
BEGIN
    SELECT email INTO v_email FROM auth.users WHERE id = p_user_id;
    
    IF v_email IS NOT NULL THEN
        DELETE FROM administradores WHERE LOWER(email) = LOWER(v_email);
    END IF;
    
    DELETE FROM auth.users WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to fetch system audit logs joined with user emails
CREATE OR REPLACE FUNCTION obtener_logs_auditoria()
RETURNS TABLE (
    id BIGINT,
    tabla VARCHAR,
    operacion VARCHAR,
    registro_id TEXT,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    fecha TIMESTAMPTZ,
    usuario_email TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a.id,
        a.tabla::VARCHAR,
        a.operacion::VARCHAR,
        a.registro_id,
        a.datos_anteriores,
        a.datos_nuevos,
        a.fecha,
        COALESCE(u.email, 'Sistema/Anónimo')::TEXT AS usuario_email
    FROM audit_log a
    LEFT JOIN auth.users u ON a.usuario_id = u.id
    ORDER BY a.fecha DESC
    LIMIT 100;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 1. Create the security backups table
CREATE TABLE IF NOT EXISTS respaldos_seguridad (
    id SERIAL PRIMARY KEY,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    creado_por TEXT DEFAULT 'Sistema (Automático)',
    productos_snapshot JSONB NOT NULL,
    movimientos_snapshot JSONB NOT NULL
);

-- Enable RLS on backing table
ALTER TABLE respaldos_seguridad ENABLE ROW LEVEL SECURITY;

-- Allow only authenticated administrators to select backups
DROP POLICY IF EXISTS "respaldos_select_policy" ON respaldos_seguridad;
CREATE POLICY "respaldos_select_policy" ON respaldos_seguridad 
    FOR SELECT TO authenticated 
    USING (EXISTS (SELECT 1 FROM administradores WHERE LOWER(email) = LOWER(auth.jwt() ->> 'email')));

-- 2. Create the snapshot function
CREATE OR REPLACE FUNCTION crear_respaldo_seguridad(p_creado_por TEXT DEFAULT 'Sistema (Automático)')
RETURNS VOID AS $$
DECLARE
    v_prod_json JSONB;
    v_mov_json JSONB;
BEGIN
    -- Capture snapshots as JSONB arrays
    SELECT COALESCE(jsonb_agg(p), '[]'::jsonb) INTO v_prod_json FROM v_productos_stock p;
    SELECT COALESCE(jsonb_agg(m), '[]'::jsonb) INTO v_mov_json FROM movimientos m;

    INSERT INTO respaldos_seguridad (creado_por, productos_snapshot, movimientos_snapshot)
    VALUES (p_creado_por, v_prod_json, v_mov_json);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Enable pg_cron and schedule it weekly on Sunday at midnight (00:00)
CREATE EXTENSION IF NOT EXISTS pg_cron;
SELECT cron.schedule('weekly-inventory-backup', '0 0 * * 0', 'SELECT crear_respaldo_seguridad()');


-- RPC to list backups (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION listar_respaldos_seguridad(p_email TEXT)
RETURNS TABLE (
    id INT,
    fecha TIMESTAMPTZ,
    creado_por TEXT
) AS $$
DECLARE
    is_admin BOOLEAN;
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM public.administradores WHERE LOWER(email) = LOWER(p_email)
    ) INTO is_admin;

    IF NOT is_admin THEN
        RAISE EXCEPTION 'Acceso denegado: El usuario no es administrador.';
    END IF;

    RETURN QUERY
    SELECT r.id, r.fecha, r.creado_por 
    FROM public.respaldos_seguridad r
    ORDER BY r.fecha DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC to fetch backup snapshots (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION obtener_respaldo_seguridad_detalle(p_email TEXT, p_respaldo_id INT)
RETURNS TABLE (
    productos_snapshot JSONB,
    movimientos_snapshot JSONB
) AS $$
DECLARE
    is_admin BOOLEAN;
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM public.administradores WHERE LOWER(email) = LOWER(p_email)
    ) INTO is_admin;

    IF NOT is_admin THEN
        RAISE EXCEPTION 'Acceso denegado: El usuario no es administrador.';
    END IF;

    RETURN QUERY
    SELECT r.productos_snapshot, r.movimientos_snapshot 
    FROM public.respaldos_seguridad r
    WHERE r.id = p_respaldo_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


