-- SQL Schema for Project Inventario (Supabase PostgreSQL)

-- 1. Create Units Table
CREATE TABLE IF NOT EXISTS unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Groups Table
CREATE TABLE IF NOT EXISTS grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS productos (
    codigo VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    unidad_id BIGINT REFERENCES unidades(id) ON DELETE RESTRICT,
    grupo_id BIGINT REFERENCES grupos(id) ON DELETE RESTRICT,
    stock_min INT DEFAULT 0 CHECK (stock_min >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Movements Table
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_codigo VARCHAR(50) REFERENCES productos(codigo) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    tipo VARCHAR(50) CHECK (tipo IN ('INGRESO', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', 'AJUSTE')),
    cantidad NUMERIC(10, 2) CHECK (cantidad > 0),
    usuario VARCHAR(255) NOT NULL,
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Create Real-Time Stock Database View
CREATE OR REPLACE VIEW v_productos_stock AS
SELECT 
    p.codigo,
    p.nombre,
    u.nombre AS unidad,
    g.nombre AS grupo,
    p.stock_min,
    COALESCE(
        SUM(
            CASE 
                WHEN m.tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE') THEN m.cantidad
                WHEN m.tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN -m.cantidad
                ELSE 0
            END
        ), 
        0
    ) AS cantidad
FROM productos p
LEFT JOIN unidades u ON p.unidad_id = u.id
LEFT JOIN grupos g ON p.grupo_id = g.id
LEFT JOIN movimientos m ON p.codigo = m.producto_codigo
GROUP BY p.codigo, p.nombre, u.nombre, g.nombre, p.stock_min;

-- 6. Insert Default Units
INSERT INTO unidades (nombre) VALUES
('Unidades'), ('Kilogramos'), ('Gramos'), ('Toneladas'), ('Litros'),
('Mililitros'), ('Metros'), ('Centímetros'), ('Metros Cuadrados'),
('Metros Cúbicos'), ('Piezas'), ('Cajas'), ('Paquetes'), ('Docenas')
ON CONFLICT (nombre) DO NOTHING;

-- 7. Insert Default Groups
INSERT INTO grupos (nombre) VALUES
('General'), ('Materia Prima'), ('Producto Terminado'), ('Producto en Proceso'),
('Herramientas'), ('Consumibles'), ('Repuestos'), ('Equipos'), ('Suministros'),
('Empaques'), ('Químicos')
ON CONFLICT (nombre) DO NOTHING;

-- 8. Enable Row Level Security (RLS)
ALTER TABLE unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos ENABLE ROW LEVEL SECURITY;

-- 9. Create Permissive Policies for the Anon Role (so client-side CRUD works)
CREATE POLICY "Allow anonymous access on unidades" ON unidades FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anonymous access on grupos" ON grupos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anonymous access on productos" ON productos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anonymous access on movimientos" ON movimientos FOR ALL TO anon USING (true) WITH CHECK (true);


