-- ============================================================
-- Cable Schedule Manager — Supabase Migration
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- 1. Master Cable Schedule (Design + Installation Tracking)
CREATE TABLE IF NOT EXISTS cable_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_unico VARCHAR(100) UNIQUE NOT NULL,

    -- Design/Engineering Data
    numero INTEGER,
    area VARCHAR(100),
    servicio VARCHAR(200),
    codigo VARCHAR(100),
    sistema VARCHAR(200),
    capacidad VARCHAR(100),
    material VARCHAR(200),
    total_estimado_m NUMERIC(10, 2) DEFAULT 0,
    conexion_origen VARCHAR(255),
    conexion_destino VARCHAR(255),
    canal_ruteo VARCHAR(255),
    tipo_cable VARCHAR(200),
    tipo_servicio VARCHAR(100),

    -- Installation Tracking
    metrado_reportado_campo NUMERIC(10, 2) DEFAULT 0,
    tendido_por VARCHAR(200),
    fecha_tendido DATE,

    -- Status
    estado VARCHAR(50) DEFAULT 'Por Tender'
        CHECK (estado IN ('Por Tender', 'Tendido', 'Conectado Origen', 'Conectado Destino', 'Terminado')),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cs_area ON cable_schedule(area);
CREATE INDEX IF NOT EXISTS idx_cs_tipo ON cable_schedule(tipo_servicio);
CREATE INDEX IF NOT EXISTS idx_cs_estado ON cable_schedule(estado);

-- 2. Warehouse Dispatching
CREATE TABLE IF NOT EXISTS cable_despachos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_unico VARCHAR(100) NOT NULL REFERENCES cable_schedule(tag_unico) ON DELETE CASCADE,

    area VARCHAR(100),
    partida VARCHAR(50),
    sector VARCHAR(200),
    area_n VARCHAR(50),
    plano_aterramiento VARCHAR(200),
    revision INTEGER DEFAULT 0,
    tag_en_plano VARCHAR(100),
    vale_almacen VARCHAR(100),
    fecha_entrega DATE,
    longitud_despachada_m NUMERIC(10, 2) DEFAULT 0,
    solicitado_por VARCHAR(200),

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cd_tag ON cable_despachos(tag_unico);

-- 3. Dashboard Aggregation View
CREATE OR REPLACE VIEW v_cable_dashboard AS
SELECT 
    cs.tag_unico,
    cs.area,
    cs.servicio,
    cs.tipo_cable,
    cs.tipo_servicio,
    cs.total_estimado_m,
    cs.metrado_reportado_campo,
    cs.conexion_origen,
    cs.conexion_destino,
    cs.estado,

    -- Tendido progress
    cs.total_estimado_m - cs.metrado_reportado_campo AS longitud_pendiente_m,
    CASE WHEN cs.metrado_reportado_campo >= cs.total_estimado_m 
         THEN true ELSE false END AS is_tendido,

    -- Despacho totals
    COALESCE(d.total_despachado, 0) AS total_despachado_m,
    COALESCE(d.num_despachos, 0) AS num_despachos

FROM cable_schedule cs
LEFT JOIN (
    SELECT 
        tag_unico,
        SUM(longitud_despachada_m) AS total_despachado,
        COUNT(*) AS num_despachos
    FROM cable_despachos
    GROUP BY tag_unico
) d ON cs.tag_unico = d.tag_unico;

-- 4. Enable Row Level Security
ALTER TABLE cable_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE cable_despachos ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read/write
CREATE POLICY "Allow authenticated read cable_schedule" ON cable_schedule
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert cable_schedule" ON cable_schedule
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update cable_schedule" ON cable_schedule
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete cable_schedule" ON cable_schedule
    FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read cable_despachos" ON cable_despachos
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert cable_despachos" ON cable_despachos
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update cable_despachos" ON cable_despachos
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete cable_despachos" ON cable_despachos
    FOR DELETE TO authenticated USING (true);
