-- Migration: Create Consumos Campo table and Balance View

-- 1. Create the table for field reported consumption
CREATE TABLE IF NOT EXISTS consumos_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_codigo VARCHAR(50) REFERENCES productos(codigo) ON DELETE CASCADE,
    descripcion_material_original TEXT,
    metrado_reportado NUMERIC(10, 2) NOT NULL,
    fecha_metrado DATE,
    area VARCHAR(100),
    plano VARCHAR(100),
    subsistema VARCHAR(100),
    tag_unico VARCHAR(100),
    upload_batch_id VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE consumos_campo ENABLE ROW LEVEL SECURITY;

-- Policies for consumos_campo
CREATE POLICY "consumos_campo_select" ON consumos_campo FOR SELECT TO authenticated USING (true);
CREATE POLICY "consumos_campo_insert" ON consumos_campo FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "consumos_campo_delete" ON consumos_campo FOR DELETE TO authenticated USING (true);

-- 2. Create the view to compare warehouse outputs vs field inputs
CREATE OR REPLACE VIEW v_balance_consumos AS
WITH WarehouseIngresos AS (
    SELECT 
        producto_codigo,
        SUM(cantidad) AS total_ingreso
    FROM movimientos
    WHERE tipo IN ('INGRESO', 'AJUSTE_POSITIVO', 'AJUSTE')
    GROUP BY producto_codigo
),
WarehouseSalidas AS (
    SELECT 
        producto_codigo,
        SUM(cantidad) AS total_salida
    FROM movimientos
    WHERE tipo IN ('SALIDA', 'AJUSTE_NEGATIVO')
    GROUP BY producto_codigo
),
FieldConsumos AS (
    SELECT 
        producto_codigo,
        SUM(metrado_reportado) AS total_consumo
    FROM consumos_campo
    GROUP BY producto_codigo
)
SELECT 
    p.codigo,
    p.nombre,
    p.grupo_id,
    g.nombre AS grupo,
    u.nombre AS unidad,
    COALESCE(i.total_ingreso, 0) AS total_ingreso,
    (COALESCE(i.total_ingreso, 0) - COALESCE(w.total_salida, 0)) AS stock_almacen,
    COALESCE(w.total_salida, 0) AS total_salida,
    COALESCE(f.total_consumo, 0) AS total_consumo,
    (COALESCE(w.total_salida, 0) - COALESCE(f.total_consumo, 0)) AS brecha,
    CASE 
        WHEN COALESCE(w.total_salida, 0) = 0 THEN 0
        ELSE ROUND(((COALESCE(w.total_salida, 0) - COALESCE(f.total_consumo, 0)) / COALESCE(w.total_salida, 0)) * 100, 2)
    END AS porcentaje_brecha
FROM productos p
LEFT JOIN grupos g ON p.grupo_id = g.id
LEFT JOIN unidades u ON p.unidad_id = u.id
LEFT JOIN WarehouseIngresos i ON p.codigo = i.producto_codigo
LEFT JOIN WarehouseSalidas w ON p.codigo = w.producto_codigo
LEFT JOIN FieldConsumos f ON p.codigo = f.producto_codigo;
