BEGIN;

CREATE TABLE IF NOT EXISTS public.project_planos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_area_id UUID NOT NULL REFERENCES public.project_areas(id) ON DELETE CASCADE,
    wbs VARCHAR(100) NOT NULL,
    sistema VARCHAR(255) NOT NULL,
    plano VARCHAR(255) NOT NULL,
    document_url TEXT NOT NULL,
    created_by UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT project_planos_nonempty CHECK (
        BTRIM(wbs) <> '' AND BTRIM(sistema) <> '' AND BTRIM(plano) <> ''
    ),
    CONSTRAINT project_planos_supported_url CHECK (
        document_url ~* '^https://([^/]+\.)?(sharepoint\.com|onedrive\.live\.com|1drv\.ms|drive\.google\.com|docs\.google\.com)/'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS project_planos_area_business_key
    ON public.project_planos (project_area_id, LOWER(wbs), LOWER(sistema), LOWER(plano));
CREATE INDEX IF NOT EXISTS project_planos_area_idx ON public.project_planos(project_area_id);

CREATE OR REPLACE FUNCTION public.can_admin_project_area(p_area_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.project_areas pa
        JOIN public.project_memberships pm ON pm.project_id = pa.project_id
        WHERE pa.id = p_area_id AND pm.user_id = auth.uid() AND pm.role = 'admin'
    );
$$;
REVOKE ALL ON FUNCTION public.can_admin_project_area(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_admin_project_area(UUID) TO authenticated;

ALTER TABLE public.project_planos ENABLE ROW LEVEL SECURITY;
CREATE POLICY project_planos_select ON public.project_planos FOR SELECT TO authenticated
    USING (public.can_access_project_area(project_area_id));
CREATE POLICY project_planos_insert ON public.project_planos FOR INSERT TO authenticated
    WITH CHECK (public.can_admin_project_area(project_area_id));
CREATE POLICY project_planos_update ON public.project_planos FOR UPDATE TO authenticated
    USING (public.can_admin_project_area(project_area_id))
    WITH CHECK (public.can_admin_project_area(project_area_id));
CREATE POLICY project_planos_delete ON public.project_planos FOR DELETE TO authenticated
    USING (public.can_admin_project_area(project_area_id));

CREATE OR REPLACE FUNCTION public.audit_project_planos_trigger()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_row public.project_planos%ROWTYPE;
BEGIN
    v_row := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    INSERT INTO public.audit_log(tabla, operacion, registro_id, datos_anteriores, datos_nuevos, usuario_id, project_area_id)
    VALUES ('project_planos', TG_OP, v_row.id::TEXT,
        CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END,
        CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END,
        auth.uid(), v_row.project_area_id);
    RETURN v_row;
END;
$$;
DROP TRIGGER IF EXISTS audit_project_planos ON public.project_planos;
CREATE TRIGGER audit_project_planos AFTER INSERT OR UPDATE OR DELETE ON public.project_planos
FOR EACH ROW EXECUTE FUNCTION public.audit_project_planos_trigger();

COMMIT;
