BEGIN;

ALTER TABLE public.cable_schedule
    ADD COLUMN IF NOT EXISTS despachado_override_m NUMERIC(12, 2);

ALTER TABLE public.cable_schedule
    DROP CONSTRAINT IF EXISTS cable_schedule_despachado_override_nonnegative;
ALTER TABLE public.cable_schedule
    ADD CONSTRAINT cable_schedule_despachado_override_nonnegative
    CHECK (despachado_override_m IS NULL OR despachado_override_m >= 0);

COMMENT ON COLUMN public.cable_schedule.despachado_override_m IS
    'Optional manually controlled dispatched total. NULL falls back to the sum of cable_despachos.';

CREATE TABLE IF NOT EXISTS public.cable_measurement_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_area_id UUID NOT NULL REFERENCES public.project_areas(id) ON DELETE RESTRICT,
    cable_schedule_id BIGINT NOT NULL REFERENCES public.cable_schedule(id) ON DELETE RESTRICT,
    tag_unico_snapshot VARCHAR(100) NOT NULL,
    wbs_snapshot VARCHAR(100),
    sistema_snapshot VARCHAR(200),
    field_name TEXT NOT NULL,
    old_value NUMERIC(12, 2) NOT NULL,
    new_value NUMERIC(12, 2) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changed_by UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
    changed_by_role TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'DATABASE',
    reason TEXT,
    CONSTRAINT cable_measurement_changes_field_check
        CHECK (field_name IN ('METRADO_OT', 'METRADO_DESPACHADO')),
    CONSTRAINT cable_measurement_changes_values_nonnegative
        CHECK (old_value >= 0 AND new_value >= 0),
    CONSTRAINT cable_measurement_changes_role_check
        CHECK (changed_by_role IN ('admin', 'supervisor', 'user'))
);

CREATE INDEX IF NOT EXISTS idx_cable_measurement_changes_area_date
    ON public.cable_measurement_changes(project_area_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_cable_measurement_changes_cable_date
    ON public.cable_measurement_changes(cable_schedule_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_cable_measurement_changes_user_date
    ON public.cable_measurement_changes(changed_by, changed_at DESC);

ALTER TABLE public.cable_measurement_changes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cable_measurement_changes_area_select ON public.cable_measurement_changes;
CREATE POLICY cable_measurement_changes_area_select
    ON public.cable_measurement_changes
    FOR SELECT TO authenticated
    USING (public.can_access_project_area(project_area_id));

CREATE OR REPLACE FUNCTION public.current_project_role_for_area(p_project_area_id UUID)
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT pm.role
    FROM public.project_areas pa
    JOIN public.project_memberships pm
      ON pm.project_id = pa.project_id
     AND pm.user_id = auth.uid()
    WHERE pa.id = p_project_area_id
      AND pm.role IN ('admin', 'supervisor', 'user')
    LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.current_project_role_for_area(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_project_role_for_area(UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.audit_cable_measurement_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_role TEXT;
    v_dispatch_sum NUMERIC(12, 2);
    v_old_dispatch NUMERIC(12, 2);
    v_new_dispatch NUMERIC(12, 2);
    v_source TEXT := COALESCE(NULLIF(current_setting('app.cable_measurement_source', TRUE), ''), 'DATABASE');
    v_reason TEXT := NULLIF(current_setting('app.cable_measurement_reason', TRUE), '');
BEGIN
    v_role := public.current_project_role_for_area(NEW.project_area_id);

    IF NEW.total_estimado_m IS DISTINCT FROM OLD.total_estimado_m THEN
        IF v_role IS DISTINCT FROM 'admin' THEN
            RAISE EXCEPTION 'Solo un administrador puede modificar METRADO OT.';
        END IF;
        IF NEW.total_estimado_m IS NULL OR NEW.total_estimado_m < 0 THEN
            RAISE EXCEPTION 'METRADO OT debe ser un numero mayor o igual a cero.';
        END IF;

        INSERT INTO public.cable_measurement_changes (
            project_area_id, cable_schedule_id, tag_unico_snapshot,
            wbs_snapshot, sistema_snapshot, field_name,
            old_value, new_value, changed_by, changed_by_role, source, reason
        ) VALUES (
            NEW.project_area_id, NEW.id, NEW.tag_unico,
            NEW.wbs, NEW.sistema, 'METRADO_OT',
            COALESCE(OLD.total_estimado_m, 0), COALESCE(NEW.total_estimado_m, 0),
            auth.uid(), v_role, v_source, v_reason
        );
    END IF;

    IF NEW.despachado_override_m IS DISTINCT FROM OLD.despachado_override_m THEN
        IF v_role IS NULL OR NOT public.can_access_project_area(NEW.project_area_id) THEN
            RAISE EXCEPTION 'No tiene permisos para modificar METRADO DESPACHADO en esta area.';
        END IF;

        SELECT COALESCE(SUM(cd.longitud_despachada_m), 0)
        INTO v_dispatch_sum
        FROM public.cable_despachos cd
        WHERE cd.cable_schedule_id = NEW.id;

        v_old_dispatch := COALESCE(OLD.despachado_override_m, v_dispatch_sum, 0);
        v_new_dispatch := COALESCE(NEW.despachado_override_m, v_dispatch_sum, 0);

        INSERT INTO public.cable_measurement_changes (
            project_area_id, cable_schedule_id, tag_unico_snapshot,
            wbs_snapshot, sistema_snapshot, field_name,
            old_value, new_value, changed_by, changed_by_role, source, reason
        ) VALUES (
            NEW.project_area_id, NEW.id, NEW.tag_unico,
            NEW.wbs, NEW.sistema, 'METRADO_DESPACHADO',
            v_old_dispatch, v_new_dispatch,
            auth.uid(), v_role, v_source, v_reason
        );
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_cable_measurements ON public.cable_schedule;
CREATE TRIGGER audit_cable_measurements
    BEFORE UPDATE OF total_estimado_m, despachado_override_m
    ON public.cable_schedule
    FOR EACH ROW
    EXECUTE FUNCTION public.audit_cable_measurement_change();

CREATE OR REPLACE FUNCTION public.actualizar_metrado_ot_cable(
    p_cable_id BIGINT,
    p_project_area_id UUID,
    p_expected_old_value NUMERIC,
    p_new_value NUMERIC,
    p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_row public.cable_schedule%ROWTYPE;
BEGIN
    IF NOT public.can_admin_project_area(p_project_area_id) THEN
        RAISE EXCEPTION 'Solo un administrador puede modificar METRADO OT.';
    END IF;
    IF p_new_value IS NULL OR p_new_value < 0 THEN
        RAISE EXCEPTION 'METRADO OT debe ser un numero mayor o igual a cero.';
    END IF;

    SELECT * INTO v_row
    FROM public.cable_schedule
    WHERE id = p_cable_id AND project_area_id = p_project_area_id
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'El cable no existe en el area activa.'; END IF;
    IF COALESCE(v_row.total_estimado_m, 0) IS DISTINCT FROM ROUND(p_expected_old_value, 2) THEN
        RAISE EXCEPTION 'METRADO OT fue modificado por otro usuario. Actualice la tabla e intente nuevamente.';
    END IF;

    PERFORM set_config('app.cable_measurement_source', 'DETALLE_CIRCUITOS', TRUE);
    PERFORM set_config('app.cable_measurement_reason', COALESCE(BTRIM(p_reason), ''), TRUE);

    UPDATE public.cable_schedule
    SET total_estimado_m = ROUND(p_new_value, 2), updated_at = NOW()
    WHERE id = p_cable_id;

    RETURN jsonb_build_object('id', p_cable_id, 'field', 'METRADO_OT', 'value', ROUND(p_new_value, 2));
END;
$$;

CREATE OR REPLACE FUNCTION public.actualizar_metrado_despachado_cable(
    p_cable_id BIGINT,
    p_project_area_id UUID,
    p_expected_old_value NUMERIC,
    p_new_value NUMERIC,
    p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_row public.cable_schedule%ROWTYPE;
    v_dispatch_sum NUMERIC(12, 2);
    v_current_value NUMERIC(12, 2);
BEGIN
    IF NOT public.can_access_project_area(p_project_area_id) THEN
        RAISE EXCEPTION 'No tiene permisos para modificar METRADO DESPACHADO en esta area.';
    END IF;
    IF p_new_value IS NULL OR p_new_value < 0 THEN
        RAISE EXCEPTION 'METRADO DESPACHADO debe ser un numero mayor o igual a cero.';
    END IF;

    SELECT * INTO v_row
    FROM public.cable_schedule
    WHERE id = p_cable_id AND project_area_id = p_project_area_id
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'El cable no existe en el area activa.'; END IF;

    SELECT COALESCE(SUM(cd.longitud_despachada_m), 0)
    INTO v_dispatch_sum
    FROM public.cable_despachos cd
    WHERE cd.cable_schedule_id = p_cable_id;
    v_current_value := COALESCE(v_row.despachado_override_m, v_dispatch_sum, 0);

    IF v_current_value IS DISTINCT FROM ROUND(p_expected_old_value, 2) THEN
        RAISE EXCEPTION 'METRADO DESPACHADO fue modificado por otro usuario. Actualice la tabla e intente nuevamente.';
    END IF;

    PERFORM set_config('app.cable_measurement_source', 'DETALLE_CIRCUITOS', TRUE);
    PERFORM set_config('app.cable_measurement_reason', COALESCE(BTRIM(p_reason), ''), TRUE);

    UPDATE public.cable_schedule
    SET despachado_override_m = ROUND(p_new_value, 2), updated_at = NOW()
    WHERE id = p_cable_id;

    RETURN jsonb_build_object('id', p_cable_id, 'field', 'METRADO_DESPACHADO', 'value', ROUND(p_new_value, 2));
END;
$$;

CREATE OR REPLACE FUNCTION public.exportar_cambios_metrado_cable(
    p_project_area_id UUID,
    p_start_date DATE,
    p_end_date DATE
)
RETURNS TABLE (
    changed_at TIMESTAMPTZ,
    area_name TEXT,
    tag_unico TEXT,
    wbs TEXT,
    sistema TEXT,
    field_name TEXT,
    old_value NUMERIC,
    new_value NUMERIC,
    difference NUMERIC,
    changed_by UUID,
    changed_by_name TEXT,
    changed_by_role TEXT,
    source TEXT,
    reason TEXT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF p_start_date IS NULL OR p_end_date IS NULL OR p_end_date < p_start_date THEN
        RAISE EXCEPTION 'Seleccione un rango de fechas valido.';
    END IF;
    IF NOT public.can_access_project_area(p_project_area_id) THEN
        RAISE EXCEPTION 'No tiene acceso al area seleccionada.';
    END IF;

    RETURN QUERY
    SELECT
        c.changed_at,
        pa.name::TEXT,
        c.tag_unico_snapshot::TEXT,
        c.wbs_snapshot::TEXT,
        c.sistema_snapshot::TEXT,
        c.field_name,
        c.old_value,
        c.new_value,
        c.new_value - c.old_value,
        c.changed_by,
        COALESCE(up.display_name, c.changed_by::TEXT)::TEXT,
        c.changed_by_role,
        c.source,
        c.reason
    FROM public.cable_measurement_changes c
    JOIN public.project_areas pa ON pa.id = c.project_area_id
    LEFT JOIN public.user_profiles up ON up.user_id = c.changed_by
    WHERE c.project_area_id = p_project_area_id
      AND c.changed_at >= (p_start_date::TIMESTAMP AT TIME ZONE 'America/Lima')
      AND c.changed_at < ((p_end_date + 1)::TIMESTAMP AT TIME ZONE 'America/Lima')
    ORDER BY c.changed_at, c.id;
END;
$$;

REVOKE ALL ON FUNCTION public.actualizar_metrado_ot_cable(BIGINT, UUID, NUMERIC, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.actualizar_metrado_despachado_cable(BIGINT, UUID, NUMERIC, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.exportar_cambios_metrado_cable(UUID, DATE, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.actualizar_metrado_ot_cable(BIGINT, UUID, NUMERIC, NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.actualizar_metrado_despachado_cable(BIGINT, UUID, NUMERIC, NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.exportar_cambios_metrado_cable(UUID, DATE, DATE) TO authenticated;

CREATE OR REPLACE VIEW public.v_cable_dashboard AS
SELECT
    cs.tag_unico,
    cs.wbs,
    cs.plano,
    cs.area,
    cs.servicio,
    cs.tipo_cable,
    cs.tipo_servicio,
    cs.total_estimado_m,
    cs.metrado_reportado_campo,
    cs.conexion_origen,
    cs.conexion_destino,
    cs.estado,
    cs.total_estimado_m - cs.metrado_reportado_campo AS longitud_pendiente_m,
    CASE WHEN cs.metrado_reportado_campo >= cs.total_estimado_m AND cs.total_estimado_m > 0
         THEN TRUE ELSE FALSE END AS is_tendido,
    COALESCE(cs.despachado_override_m, d.total_despachado, 0) AS total_despachado_m,
    COALESCE(d.num_despachos, 0) AS num_despachos
FROM public.cable_schedule cs
LEFT JOIN (
    SELECT cable_schedule_id,
           SUM(longitud_despachada_m) AS total_despachado,
           COUNT(*) AS num_despachos
    FROM public.cable_despachos
    GROUP BY cable_schedule_id
) d ON d.cable_schedule_id = cs.id;

ALTER VIEW public.v_cable_dashboard SET (security_invoker = TRUE);

COMMIT;
33333