BEGIN;

CREATE TABLE IF NOT EXISTS public.project_plano_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_area_id UUID NOT NULL REFERENCES public.project_areas(id) ON DELETE CASCADE,
    partition VARCHAR(100) NOT NULL,
    wbs VARCHAR(100) NOT NULL,
    folder_url TEXT,
    created_by UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT project_plano_groups_nonempty CHECK (BTRIM(partition) <> '' AND BTRIM(wbs) <> ''),
    CONSTRAINT project_plano_groups_supported_url CHECK (
        folder_url ~* '^https://([^/]+\.)?(sharepoint\.com|onedrive\.live\.com|1drv\.ms|drive\.google\.com|docs\.google\.com)/'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS project_plano_groups_business_key
    ON public.project_plano_groups (project_area_id, LOWER(partition), LOWER(wbs));
CREATE INDEX IF NOT EXISTS project_plano_groups_area_partition_idx
    ON public.project_plano_groups (project_area_id, partition);

INSERT INTO public.project_plano_groups (project_area_id, partition, wbs, folder_url, created_by)
SELECT DISTINCT ON (project_area_id, LOWER(partition), LOWER(wbs))
       project_area_id, partition, wbs, document_url, created_by
FROM public.project_planos
ORDER BY project_area_id, LOWER(partition), LOWER(wbs), id
ON CONFLICT DO NOTHING;

ALTER TABLE public.project_planos
    ADD COLUMN IF NOT EXISTS group_id BIGINT REFERENCES public.project_plano_groups(id) ON DELETE RESTRICT;

UPDATE public.project_planos drawing
SET group_id = drawing_group.id
FROM public.project_plano_groups drawing_group
WHERE drawing.group_id IS NULL
  AND drawing.project_area_id = drawing_group.project_area_id
  AND LOWER(drawing.partition) = LOWER(drawing_group.partition)
  AND LOWER(drawing.wbs) = LOWER(drawing_group.wbs);

ALTER TABLE public.project_planos ALTER COLUMN document_url DROP NOT NULL;

UPDATE public.project_planos SET document_url = NULL WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS project_planos_group_idx ON public.project_planos(group_id);

ALTER TABLE public.project_plano_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY project_plano_groups_select ON public.project_plano_groups FOR SELECT TO authenticated
    USING (public.can_access_project_area(project_area_id));
CREATE POLICY project_plano_groups_insert ON public.project_plano_groups FOR INSERT TO authenticated
    WITH CHECK (public.can_admin_project_area(project_area_id));
CREATE POLICY project_plano_groups_update ON public.project_plano_groups FOR UPDATE TO authenticated
    USING (public.can_admin_project_area(project_area_id))
    WITH CHECK (public.can_admin_project_area(project_area_id));
CREATE POLICY project_plano_groups_delete ON public.project_plano_groups FOR DELETE TO authenticated
    USING (public.can_admin_project_area(project_area_id));

CREATE OR REPLACE FUNCTION public.prevent_project_plano_group_identity_update()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
    IF NEW.project_area_id IS DISTINCT FROM OLD.project_area_id
       OR NEW.partition IS DISTINCT FROM OLD.partition
       OR NEW.wbs IS DISTINCT FROM OLD.wbs THEN
        RAISE EXCEPTION 'PARTITION, WBS and project area cannot be edited. Delete and recreate the group instead.';
    END IF;
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;
CREATE TRIGGER prevent_project_plano_group_identity_update
    BEFORE UPDATE ON public.project_plano_groups
    FOR EACH ROW EXECUTE FUNCTION public.prevent_project_plano_group_identity_update();

COMMIT;
