-- Create the import_profiles table
CREATE TABLE IF NOT EXISTS import_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL, -- e.g., 'Procura Ingresos', 'Almacen Salidas'
    type VARCHAR(50) CHECK (type IN ('ingresos', 'salidas', 'cables')),
    signature_columns TEXT[] NOT NULL, -- array of columns used to auto-identify the file type
    required_columns TEXT[] NOT NULL,  -- mandatory columns (e.g., TRANSACTION KEY)
    column_mapping JSONB NOT NULL,     -- e.g., {"TRANSACTION KEY": "key", "CantRecep.": "cantidad"}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE import_profiles ENABLE ROW LEVEL SECURITY;

-- Allow read access for authenticated users
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON import_profiles;
CREATE POLICY "Allow read access to authenticated users" ON import_profiles
    FOR SELECT TO authenticated USING (true);

-- Allow write access to authenticated administrators
DROP POLICY IF EXISTS "Allow write access to authenticated administrators" ON import_profiles;
CREATE POLICY "Allow write access to authenticated administrators" ON import_profiles
    FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM administradores WHERE LOWER(email) = LOWER(auth.jwt() ->> 'email')));

-- Seed standard profiles
INSERT INTO import_profiles (name, type, signature_columns, required_columns, column_mapping)
VALUES 
(
  'Procura Ingresos', 
  'ingresos', 
  ARRAY['Disciplina', 'TRANSACTION KEY', 'DESCRIPCION'], 
  ARRAY['TRANSACTION KEY', 'DESCRIPCION', 'CantRecep.', 'UMP'], 
  '{"TRANSACTION KEY": "key", "DESCRIPCION": "producto", "CantRecep.": "cantidad", "UMP": "unidad", "F.Rec.Proy": "fecha", "Disciplina": "disciplina", "Fec.Creac.": "fecha_fallback"}'::jsonb
),
(
  'Almacen Salidas', 
  'salidas', 
  ARRAY['Cód.Almacenero', 'Descr. Artículo', 'Cant. entregada'], 
  ARRAY['Nro', 'Descr. Artículo', 'Cant. entregada', 'UM', 'Cód.Almacenero'], 
  '{"Nro": "key", "Descr. Artículo": "producto", "Cant. entregada": "cantidad", "UM": "unidad", "Fecha de pedido": "fecha", "Cód.Almacenero": "almacenero"}'::jsonb
)
ON CONFLICT (name) DO UPDATE 
SET 
  type = EXCLUDED.type,
  signature_columns = EXCLUDED.signature_columns,
  required_columns = EXCLUDED.required_columns,
  column_mapping = EXCLUDED.column_mapping;
