-- Migration: Create Bill of Materials (BOM) / Recetas for products

-- Create new group for Ensambles/Actividades if it doesn't exist
INSERT INTO grupos (nombre) VALUES ('Ensambles/Actividades')
ON CONFLICT (nombre) DO NOTHING;

-- 1. Create the BOM table (producto_recetas)
CREATE TABLE IF NOT EXISTS producto_recetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_codigo VARCHAR(50) NOT NULL REFERENCES productos(codigo) ON DELETE CASCADE,
    componente_codigo VARCHAR(50) NOT NULL REFERENCES productos(codigo) ON DELETE RESTRICT,
    multiplicador NUMERIC(14, 4) NOT NULL CHECK (multiplicador > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE (parent_codigo, componente_codigo)
);

-- Enable RLS
ALTER TABLE producto_recetas ENABLE ROW LEVEL SECURITY;

-- Policies for producto_recetas
CREATE POLICY "producto_recetas_select" ON producto_recetas FOR SELECT TO authenticated USING (true);
CREATE POLICY "producto_recetas_insert" ON producto_recetas FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "producto_recetas_update" ON producto_recetas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "producto_recetas_delete" ON producto_recetas FOR DELETE TO authenticated USING (true);
